<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <TargetPlatformIdentifier>Windows</TargetPlatformIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>EqlGearHelper.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Include="TngTech.ArchUnitNET" Version="0.13.3" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnit" Version="0.13.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\EqlGearHelper.Wpf\EqlGearHelper.Wpf.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
